apiVersion: v1
kind: Namespace
metadata:
  name: archivist-test-namespace
  labels:
    name: archivist-test-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivist-demo
  namespace: archivist-test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      archivist-node: dist-test
  template:
    metadata:
      labels:
        archivist-node: dist-test
    spec:
      containers:
      - name: archivist-node1
        image: durabilitylabs/archivist-node:sha-9817b12
        ports:
        - containerPort: 8080
          name: api-1
        env:
        - name: API_PORT
          value: "8080"
        - name: DATA_DIR
          value: datadir1
        - name: DISC_PORT
          value: "8081"
        - name: LISTEN_ADDRS
          value: "/ip4/0.0.0.0/tcp/8082"
      - name: archivist-node2
        image: durabilitylabs/archivist-node:sha-9817b12
        ports:
        - containerPort: 8083
          name: api-2
        env:
        - name: API_PORT
          value: "8083"
        - name: DATA_DIR
          value: datadir2
        - name: DISC_PORT
          value: "8084"
        - name: LISTEN_ADDRS
          value: "/ip4/0.0.0.0/tcp/8085"
          
---

apiVersion: v1
kind: Service
metadata:
  name: archivist-entrypoint
  namespace: archivist-test-namespace
spec:
  type: NodePort
  selector:
    archivist-node: dist-test
  ports:
  - name: "node1"
    protocol: TCP
    port: 8080
    targetPort: api-1
    nodePort: 30001
  - name: "node2"
    protocol: TCP
    port: 8083
    targetPort: api-2
    nodePort: 30002

