openapi: 3.0.3
info:
  title: ArchivistGatewayService
  version: "1.0"

# Components and response types are copied from
# the Archivist openapi.yaml.

components:
  schemas:
    Cid:
      type: string
      description: Content Identifier as specified at https://github.com/multiformats/cid
      example: QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N
      
    DataItem:
      type: object
      required:
        - cid
        - manifest
      properties:
        cid:
          $ref: "#/components/schemas/Cid"
        manifest:
          $ref: "#/components/schemas/ManifestItem"

    ManifestItem:
      type: object
      required:
        - treeCid
        - datasetSize
        - blockSize
        - protected
      properties:
        treeCid:
          $ref: "#/components/schemas/Cid"
          description: "Unique data identifier"
        datasetSize:
          type: integer
          format: int64
          description: "Length of original content in bytes"
        blockSize:
          type: integer
          description: "Size of blocks"
        protected:
          type: boolean
          description: "Indicates if content is protected by erasure-coding"
        filename:
          type: string
          nullable: true
          description: "The original name of the uploaded content (optional)"
          example: example.png
        mimetype:
          type: string
          nullable: true
          description: "The original mimetype of the uploaded content (optional)"
          example: image/png

paths:
  /manifest/{cid}:
    get:
      tags:
        - Gateway
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Manifest information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataItem"
        "400":
          description: Invalid CID is specified
        "404":
          description: Failed to download dataset manifest
        "500":
          description: Well it was bad-bad

  /data/{cid}:
    get:
      tags:
        - Gateway
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Retrieved content specified by CID
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Invalid CID is specified
        "404":
          description: Content specified by the CID is not found
        "500":
          description: Well it was bad-bad
