services:
  dist-test-run:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - ARCHIVISTDOCKERIMAGE=durabilitylabs/archivist-node:latest-dist-tests
      - BRANCH=main
      - KUBECONFIG=/opt/kubeconfig
      - LOGPATH=/opt/logs
    volumes:
      - /path/to/kubeconfig:/opt/kubeconfig
