{
 "title": "Archivist",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "API Upload/Download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "archivistApiUploads_total" }
   ]
  },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "archivistApiDownloads_total" }
   ]
  },
  { "title": "Local Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "archivistRepostoreBlocks" }
   ]
  },
  {
   "title": "Bytes reserved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "archivistRepostoreBytesReserved"
    }
   ]
  },
  {
   "title": "Bytes used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "archivistRepostoreBytesUsed" }
   ]
  },
  { "title": "Network Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "Routing table nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    { "expr": "routing_table_nodes" }
   ]
  },
  { "title": "Block Exchange", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Blocks sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "archivistBlockExchangeBlocksSent_total"
    }
   ]
  },
  {
   "title": "Blocks received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "archivistBlockExchangeBlocksReceived_total"
    }
   ]
  },
  {
   "title": "WantHave lists sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "archivistBlockExchangeWantHaveListsSent_total"
    }
   ]
  },
  {
   "title": "WantBlock lists sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "archivistBlockExchangeWantBlockListsSent_total"
    }
   ]
  },
  {
   "title": "WantHave lists received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "archivistBlockExchangeWantHaveListsReceived_total"
    }
   ]
  },
  {
   "title": "WantBlock lists received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "archivistBlockExchangeWantBlockListsReceived_total"
    }
   ]
  },
  { "title": "Purchases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "archivistPurchasesPending_total"
    }
   ]
  },
  {
   "title": "Submitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "archivistPurchasesSubmitted_total"
    }
   ]
  },
  {
   "title": "Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "archivistPurchasesStarted_total"
    }
   ]
  },
  {
   "title": "Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "archivistPurchasesFinished_total"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "targets": [
    { "expr": "archivistPurchasesFailed_total" }
   ]
  },
  {
   "title": "Cancelled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "archivistPurchasesCancelled_total"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "archivistPurchasesUnknown_total"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "targets": [
    { "expr": "archivistPurchasesError_total" }
   ]
  }
 ]
}