name: Docker - Rewarder Bot


on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - 'Tools/TestNetRewarder/**'
      - '!Tools/TestNetRewarder/docker/docker-compose.yaml'
      - 'Framework/**'
      - 'ProjectPlugins/**'
      - .github/workflows/docker-rewarder.yml
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: durability-labs/github-actions/.github/workflows/docker-reusable.yml@main
    with:
      docker_file: Tools/TestNetRewarder/docker/Dockerfile
      dockerhub_repo: durabilitylabs/archivist-rewarderbot
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
