name: Docker - Runner


on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - docker/Dockerfile
      - docker/docker-entrypoint.sh
      - .github/workflows/docker-runner.yml
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: durability-labs/github-actions/.github/workflows/docker-reusable.yml@main
    with:
      docker_file: docker/Dockerfile
      dockerhub_repo: durabilitylabs/cs-archivist-dist-tests
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
